version: "2.1"

services:

  dynamodb:
    build: dynamodb/.
    image: chaossystems/dynamodb:${CIRCLE_BUILD_NUM:-local}
    image: chaossystems/dynamodb:${CIRCLE_BRANCH:-local}

  oraclejdk8:
    build: java/oracle-jdk-8/.
    image: chaossystems/oraclejdk8:${CIRCLE_BUILD_NUM:-local}
    image: chaossystems/oraclejdk8:${CIRCLE_BRANCH:-local}

  swift2:  
    build: swift/2/.
    image: chaossystems/swift:2.2.1
    image: chaossystems/swift:2
  
  swift3:  
    build: swift/3/.
    image: chaossystems/swift:3.0.2
    image: chaossystems/swift:3
  
  ubuntu-devtools:  
    build: shell/ubuntu-devtools/.
    image: chaossystems/ubuntu-devtools:${CIRCLE_BUILD_NUM:-local}
    image: chaossystems/ubuntu-devtools:${CIRCLE_BRANCH:-local}
  
  ubuntu-cloudtools:  
    build: shell/ubuntu-cloudtools/.
    image: chaossystems/ubuntu-cloudtools:${CIRCLE_BUILD_NUM:-local}
    image: chaossystems/ubuntu-cloudtools:${CIRCLE_BRANCH:-local}
    depends_on: [ubuntu-devtools]
