version: "2.1"

services:

  dynamodb:
    build: dynamodb/.
    image: chaossystems/dynamodb:${CIRCLE_BUILD_NUM:-local}

  oraclejdk8:
    build: java/oracle-jdk-8/.
    image: chaossystems/oraclejdk8:${CIRCLE_BUILD_NUM:-local}

  swift:
    build: swift/3/.
    image: chaossystems/swift:3.1.0

  ubuntu-devtools:  
    build: shell/ubuntu-devtools/.
    image: chaossystems/ubuntu-devtools:${CIRCLE_BUILD_NUM:-local}

  ubuntu-cloudtools:  
    build: shell/ubuntu-cloudtools/.
    image: chaossystems/ubuntu-cloudtools:${CIRCLE_BUILD_NUM:-local}
    depends_on: [ubuntu-devtools]
