version: "3.1"

services:

  dynamodb:
    build: dynamodb/.
    image: chaossystems/dynamodb:${CIRCLE_BUILD_NUM:-local}

  swift:
    build: swift/3/.
    image: chaossystems/swift:3.1.1

  ubuntu-devtools:  
    build: shell/ubuntu-devtools/.
    image: chaossystems/ubuntu-devtools:${CIRCLE_BUILD_NUM:-local}

  ubuntu-cloudtools:  
    build: shell/ubuntu-cloudtools/.
    image: chaossystems/ubuntu-cloudtools:${CIRCLE_BUILD_NUM:-local}
    depends_on: [ubuntu-devtools]

  fedora-devtools:
    build: shell/fedora-devtools/.
    image: chaossystems/fedora-devtools:${CIRCLE_BUILD_NUM:-local}

  fedora-cloudtools:
    build: shell/fedora-cloudtools/.
    image: chaossystems/fedora-cloudtools:${CIRCLE_BUILD_NUM:-local}
    depends_on: [fedora-devtools]
