FROM ubuntu:latest
MAINTAINER Greg Orzell <chaos@chaossystems.io>

# Install Open JDK Java 8

RUN apt-get update && \
    apt-get install -y --force-yes --no-install-recommends openjdk-8-jdk && \
    apt-get clean 

